// <auto-generated />
using System;
using FinanceHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321002119_InitialCreateWithCategories")]
    partial class InitialCreateWithCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FinanceHub.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#f59e0b",
                            Icon = "🍕",
                            Name = "Food & Dining"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3b82f6",
                            Icon = "🚗",
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#a855f7",
                            Icon = "🎬",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ec4899",
                            Icon = "🛍️",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#eab308",
                            Icon = "💡",
                            Name = "Bills & Utilities"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#10b981",
                            Icon = "🏥",
                            Name = "Health & Fitness"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#22c55e",
                            Icon = "💰",
                            Name = "Income"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6b7280",
                            Icon = "📦",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("FinanceHub.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50.00m,
                            CategoryId = 1,
                            Date = new DateTime(2026, 3, 19, 10, 21, 19, 71, DateTimeKind.Local).AddTicks(9022),
                            Description = "Lunch at cafe",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2000.00m,
                            CategoryId = 7,
                            Date = new DateTime(2026, 3, 16, 10, 21, 19, 71, DateTimeKind.Local).AddTicks(9033),
                            Description = "Monthly salary",
                            Type = "income"
                        });
                });

            modelBuilder.Entity("FinanceHub.Models.Transaction", b =>
                {
                    b.HasOne("FinanceHub.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceHub.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
