// <auto-generated />
using System;
using FinanceHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320233624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FinanceHub.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50.00m,
                            Category = "food",
                            Date = new DateTime(2026, 3, 16, 9, 36, 21, 340, DateTimeKind.Local).AddTicks(6836),
                            Description = "Initial test transaction",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000.00m,
                            Category = "income",
                            Date = new DateTime(2026, 3, 11, 9, 36, 21, 340, DateTimeKind.Local).AddTicks(6850),
                            Description = "Test salary",
                            Type = "income"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
